%% Diagrama de Componentes - Sistema Patas & Bigodes
%% Representacao Mermaid aproximada da notacao lollipop UML.

flowchart LR
    Utilizador([Utilizador])

    subgraph Controllers["pt.hotel.animais.controller"]
        AuthController["<<component>><br/>AuthController"]
        DashboardController["<<component>><br/>DashboardController"]
        AlojamentoController["<<component>><br/>AlojamentoController"]
        TutorAnimalController["<<component>><br/>TutorAnimalController"]
        AnimalController["<<component>><br/>AnimalController"]
        ReservaController["<<component>><br/>ReservaController"]
        EstadiaController["<<component>><br/>EstadiaController"]
        PagamentoController["<<component>><br/>PagamentoController"]
        RegistoCuidadoController["<<component>><br/>RegistoCuidadoController"]
        PlanoCuidadosController["<<component>><br/>PlanoCuidadosController"]
        NotaController["<<component>><br/>NotaController"]
        ServicoExtraController["<<component>><br/>ServicoExtraController"]
        ClinicaController["<<component>><br/>ClinicaController"]
        LimpezaController["<<component>><br/>LimpezaController"]
        HistoricoController["<<component>><br/>HistoricoController"]
        RelatorioController["<<component>><br/>RelatorioController"]
        ColaboradorController["<<component>><br/>ColaboradorController"]
        TipoAlojamentoTarifaController["<<component>><br/>TipoAlojamentoTarifaController"]
        TipoServicoExtraController["<<component>><br/>TipoServicoExtraController"]
        AuditoriaController["<<component>><br/>AuditoriaController"]
    end

    subgraph Services["pt.hotel.animais.service"]
        ColaboradorService["<<component>><br/>ColaboradorService"]
        DashboardService["<<component>><br/>DashboardService"]
        AlojamentoService["<<component>><br/>AlojamentoService"]
        TutorService["<<component>><br/>TutorService"]
        AnimalService["<<component>><br/>AnimalService"]
        ReservaService["<<component>><br/>ReservaService"]
        EstadiaService["<<component>><br/>EstadiaService"]
        PagamentoService["<<component>><br/>PagamentoService"]
        RegistoCuidadoService["<<component>><br/>RegistoCuidadoService"]
        PlanoCuidadosService["<<component>><br/>PlanoCuidadosService"]
        NotaService["<<component>><br/>NotaService"]
        ServicoExtraService["<<component>><br/>ServicoExtraService"]
        ClinicaService["<<component>><br/>ClinicaService"]
        IntervencaoClinicaService["<<component>><br/>IntervencaoClinicaService"]
        AlteracaoEstadoSaudeService["<<component>><br/>AlteracaoEstadoSaudeService"]
        LimpezaService["<<component>><br/>LimpezaService"]
        HistoricoService["<<component>><br/>HistoricoService"]
        RelatorioService["<<component>><br/>RelatorioService"]
        TipoAlojamentoTarifaService["<<component>><br/>TipoAlojamentoTarifaService"]
        TipoServicoExtraService["<<component>><br/>TipoServicoExtraService"]
        RegraDominioService["<<component>><br/>RegraDominioService"]
        AvailabilityDomainService["<<component>><br/>AvailabilityDomainService"]
    end

    subgraph AuditoriaServices["pt.hotel.animais.service.auditoria"]
        AuditoriaService["<<component>><br/>AuditoriaService"]
        AuditoriaOperacaoService["<<component>><br/>AuditoriaOperacaoService"]
    end

    subgraph Repositories["pt.hotel.animais.repository"]
        ColaboradorRepository["<<component>><br/>ColaboradorRepository"]
        AlojamentoRepository["<<component>><br/>AlojamentoRepository"]
        TutorRepository["<<component>><br/>TutorRepository"]
        AnimalRepository["<<component>><br/>AnimalRepository"]
        ReservaRepository["<<component>><br/>ReservaRepository"]
        EstadiaRepository["<<component>><br/>EstadiaRepository"]
        PagamentoRepository["<<component>><br/>PagamentoRepository"]
        RegistoCuidadoRepository["<<component>><br/>RegistoCuidadoRepository"]
        PlanoCuidadosRepository["<<component>><br/>PlanoCuidadosRepository"]
        TarefaCuidadoRepository["<<component>><br/>TarefaCuidadoRepository"]
        NotaRepository["<<component>><br/>NotaRepository"]
        ServicoExtraRepository["<<component>><br/>ServicoExtraRepository"]
        TipoServicoExtraRepository["<<component>><br/>TipoServicoExtraRepository"]
        IntervencaoClinicaRepository["<<component>><br/>IntervencaoClinicaRepository"]
        AlteracaoEstadoSaudeRepository["<<component>><br/>AlteracaoEstadoSaudeRepository"]
        TipoAlojamentoTarifaRepository["<<component>><br/>TipoAlojamentoTarifaRepository"]
        AuditoriaRepository["<<component>><br/>AuditoriaRepository"]
    end

    IColaboradorService(("IColaboradorService"))
    IDashboardService(("IDashboardService"))
    IAlojamentoService(("IAlojamentoService"))
    ITutorService(("ITutorService"))
    IAnimalService(("IAnimalService"))
    IReservaService(("IReservaService"))
    IEstadiaService(("IEstadiaService"))
    IPagamentoService(("IPagamentoService"))
    IRegistoCuidadoService(("IRegistoCuidadoService"))
    IPlanoCuidadosService(("IPlanoCuidadosService"))
    INotaService(("INotaService"))
    IServicoExtraService(("IServicoExtraService"))
    IClinicaService(("IClinicaService"))
    IIntervencaoClinicaService(("IIntervencaoClinicaService"))
    IAlteracaoEstadoSaudeService(("IAlteracaoEstadoSaudeService"))
    ILimpezaService(("ILimpezaService"))
    IHistoricoService(("IHistoricoService"))
    IRelatorioService(("IRelatorioService"))
    IRegraDominioService(("IRegraDominioService"))
    IAvailabilityDomainService(("IAvailabilityDomainService"))
    IAuditoriaService(("IAuditoriaService"))

    DB[("hotelanimais")]

    Utilizador --> AuthController
    Utilizador --> DashboardController

    ColaboradorService --- IColaboradorService
    DashboardService --- IDashboardService
    AlojamentoService --- IAlojamentoService
    TutorService --- ITutorService
    AnimalService --- IAnimalService
    ReservaService --- IReservaService
    EstadiaService --- IEstadiaService
    PagamentoService --- IPagamentoService
    RegistoCuidadoService --- IRegistoCuidadoService
    PlanoCuidadosService --- IPlanoCuidadosService
    NotaService --- INotaService
    ServicoExtraService --- IServicoExtraService
    ClinicaService --- IClinicaService
    IntervencaoClinicaService --- IIntervencaoClinicaService
    AlteracaoEstadoSaudeService --- IAlteracaoEstadoSaudeService
    LimpezaService --- ILimpezaService
    HistoricoService --- IHistoricoService
    RelatorioService --- IRelatorioService
    RegraDominioService --- IRegraDominioService
    AvailabilityDomainService --- IAvailabilityDomainService
    AuditoriaService --- IAuditoriaService

    Controllers -.-> Services
    Controllers -.-> AuditoriaServices
    Services -.-> AuditoriaServices
    Services -.-> Repositories
    AuditoriaServices -.-> Repositories
    Repositories --> DB
